baseURL = "http://claygardner.io/"
languageCode = "en-us"
title = "Clay's Blog"
theme = "hugo-theme-cactus-plus"
disqusShortname = ""

[params]
	name = "Clay Gardner"
	description = "Software engineering blog"
	bio = "Self starting, product focused software engineer."
	enableRSS = false

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "home"
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = " "
	# Sharing options and author information in posts
	aboutAuthor = "I write code."
	tweet = ""
	share = ""
	# 404 page
	title404 = "Page not found"
	subtitle404 = "The page you are looking for does not exist."

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    linkedin  = "https://www.linkedin.com/in/gardncl/"
    github   = "https://www.github.com/gardncl"